### ISSUE TITLE
Cant Pull This Image "ghcr.io/notifirehq/notifire/sdk:latest "

### ISSUE THREAD

**Issue by eugenewere** [notifirehq/notifire#353]
I am getting this error:

Error response from daemon: Head "https://ghcr.io/v2/notifirehq/notifire/sdk/manifests/latest": denied

**Comment by scopsy** [comment]
Hi @eugenewere yes we still working on the upcoming release and the SDK docker image is not pushed yet to the ghcr repository. I believe it will be pushed during this week. I will update this asap. 

In the meantime, you can clone the repo and run it locally using "pnpm start". I will let you know once the SDK image is up

**Comment by eugenewere** [comment]
Thanks alot

**Comment by scopsy** [comment]
Hi @eugenewere published the missing SDK library 🎊, we currently facing an issue due to the dynamic environment variables passing to the "web" and "widget" project that requires quite a lot of resources when running the docker. This is tracked at #378 closing this issue for now as it is resolved, but the run optimization will be tracked there.
