### ISSUE TITLE
Move Sendgrid setApiKey to sendMessage

### ISSUE THREAD

**Issue by nevo-david** [notifirehq/notifire#373]
### What? 

We might want to load multiple Sendgrid providers in the future.
The Sendgrid API key is being defined in the constructor, but statically.
It means that every new Sendgrid instance we make will override the previous one.

## How to reproduce

* Register 2 SendGrid providers, put the second one to be invalid.
* Run the trigger

(This issue is valid after the provider's tasks)

**Comment by scopsy** [comment]
This is not really I direction we want to take since it will require updating all the current providers not only SendGrid to this paradigm. This means we are breaking the responsibilities and border between a trigger and a trigger. 

If someone wants to register to duplicate send grid provider he needs to be able to register 2 providers with different IDs. Please refer to #14, in that case, you can just register 2 providers with different IDs.

We need to create the separation of concerns between the 3 main concepts:
- Provider
- Template
- Trigger

Putting the setApiKey breaks the separation as it requires that the trigger be familiar with the concept of SendGrid or its presence of it.

Let me know what you think, but we will probably close this issue.
