### ISSUE TITLE
Add new AWS SES email provider

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#39]
### What?
New [SES](https://github.com/aws/aws-sdk-js) Email Provider

### Why?
To have the ability to use [SES](https://github.com/aws/aws-sdk-js)  as a provider.

### How?
Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### Usage
Example for SES provider registration needs to be finalized. 

```ts
await notifire.registerProvider(
  new SESEmailProvider({
    from: "support@supercorp.io",
    accessKeyId: process.env.SES_ACCESS_KEY,
    secretAccessKey: process.env.SES_SECRET_KEY,
    region: process.env.SES_REGION
  })
);
```

### Notes
This [blog](https://betterprogramming.pub/how-to-send-emails-with-node-js-using-amazon-ses-8ae38f6312e4) by [EJ Ozyazgan](https://github.com/EJOzyazgan) can be used as reading material, as well as this [article](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html) by AWS team, or this [blog post](https://medium.com/@maciej.lisowski.elk/nodejs-and-amazon-ses-how-to-send-emails-from-your-application-5c24b1f9b67b) by Mac Lisowski(https://github.com/maclisowski).

**Comment by ivorpad** [comment]
I'm interested in taking this, I don't care if it's hacktoberfest 😅 but I need AWS SES and I really like Notifire's API. I might also create a Nest.js module.

How should the API look with all the *send* methods AWS SES has?

- sendEmail
- sendRawEmail
- sendTemplatedEmail
- sendBulkTemplatedEmail

I ask because we have this trigger method: `trigger(eventId: string, data: ITriggerPayload): Promise<void>;` so maybe we can pass a trigger `type`?

I'm not sure we should support `sendTemplatedEmail` because Notifire already has handlebars support.

Anyways, open to discussion!

**Comment by ComBarnea** [comment]
Hey @ivorpad it looks ulentini, just created a PR for this, I am opening a new issue for NestJS module, care to take that? I'll mention you there as well

**Comment by ivorpad** [comment]
@ComBarnea Sure thing. Yeah I didn't had time this week to work on anything else.
