### ISSUE TITLE
🐛 Bug Report: LogDecorator mistakenly redacted function parameters when LoggingLevel = debug 

### ISSUE THREAD

**Issue by tam-endue** [notifirehq/notifire#5655]
### 📜 Description

When `LOGGING_LEVEL` set to debug, the `@LogDecorator` set methods parameters that are sensitive fields like email to `REDACTED`, which lead to issue with the api `/widgets/session/initialize`, which ever body param sent, it will always return "Email must be an email" error message. 

### 👟 Reproduction steps

1. Set LOGGING_LEVEL to debug 
2. Initialize session using `/widgets/session/initialize`

### 👍 Expected behavior

Initialize session successfully and return token 

### 👎 Actual Behavior with Screenshots

```
InitializeSessionCommand {
  subscriberId: 'endue199381',
  applicationIdentifier: 'xxxxx',
  email: '[REDACTED]',
  firstName: '[REDACTED]',
  lastName: '[REDACTED]',
  phone: '[REDACTED]',
  hmacHash: 'xyz'
}
```

### Novu version

0.24.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by tam-endue** [comment]
@scopsy look like you knows the `LogDecorator` class well, maybe you want to take a look

**Comment by rifont** [comment]
Thanks for reporting this @tam-endue .

We've encountered this issue too (Linear ref: [NV-3274](https://linear.app/novu/issue/NV-3274/the-nestjs-logger-is-mutating-objects)) . We traced the root cause back to `fast-redact` as a 4th layer transitive dependency of `nestjs-pino`, which mutates the objects passed for redaction in place.

Unfortunately the [fix](https://github.com/davidmarkclements/fast-redact/pull/59) hasn't yet arrived in our direct dependency. Our only option as of now is to specify an `overrides` in the monorepo root `package.json` to manually specify the fix version.

Would you be open to submitting a PR for this fix?
