### ISSUE TITLE
Missing docs for provider template command

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#67]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
A new provider template command was added in #61. Documentation is missing in [how to add a provider](https://docs.notifire.co/docs/community/create-provider)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

A new section with a title called initialization,  description, and code snippet needs to be added.

**Comment by cloudguruab** [comment]
@ComBarnea I'd like to tackle this issue if it hasnt been done already!

**Comment by scopsy** [comment]
Amazing @cloudguruab Let me know if you need any help

**Comment by cloudguruab** [comment]
Sweet, thanks! Will do.

**Comment by cloudguruab** [comment]
### Notes 
Problem statement: 
```
#whats missing
Other information (e.g. detailed explanation, stack traces, related issues, 
suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

#outcome
A new section with a title called initialization, description, and code snippet needs to be added.
```

- [ ] Gather resources
- [ ] Review current docs and iterate through setup
- [ ] Retrospective of experience, along with solutions to any roadblocks 
- [ ] Collect notes and complete `outcome` section above

**Comment by cloudguruab** [comment]
@scopsy I have a question in regards to issue #54, I noticed the needed changes to implement a tool that allows for auto generation of code. I wanted to know what exactly is a provider? Is this entities like sendGrid, or is this something completely else? I noticed in #61 Hygen was added to accomplish auto generating templates for providers, so I am just trying to make a few connections here.

**Comment by cloudguruab** [comment]
Also what prompted this change as well?

**Comment by scopsy** [comment]
@cloudguruab Sure!

So a provider is an entity that handles the delivery of a message over multiple channels:
- SendGrid - For email
- Twillio - SMS
- Onesignal - Push
- Webpush
- Slack - Direct

We have multiple providers for each channel(SMS, Email, Push, Web-Push, Direct and others).
For now, we have only about 10 providers but there are a lot more we haven't created. To create new provider easily and help new contributors with that, we create a code generator using hygen. To create a new provider you need to:
Setup the repository locally and run: `yarn install` in the root of the project, and build the `core` package: `cd packages/core && yarn run build`

After the project was initialized the project to create a new provider a contributor needs to run `yarn run generate:provider` from the root of the repo, this will prompt him to enter the type of the provider and its name. After that, a new folder will be generated for the new provider. Depending on the channel, the implementation details will need to be added in the provider file.
After that, a unit test should be added as well, and preferably this should be tested manually with the provider itself end-to-end.

Later on create a PR, and we can add the provider to our providers list :)

The goal of this issue is to update the current add new provider doc page to tell all the things I've written above in a readable manner 😅

You can feel free to add snippets and enrich it with the information you find useful. 
I'm available for any help you need here, or on our discord :)

**Comment by scopsy** [comment]
> ### Notes
> Problem statement:
> 
> ```
> #whats missing
> Other information (e.g. detailed explanation, stack traces, related issues, 
> suggestions on how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
> 
> #outcome
> A new section with a title called initialization, description, and code snippet needs to be added.
> ```
> 
> * [x]  Gather resources
> * [ ]  Review current docs and iterate through setup
> * [ ]  Retrospective of experience, along with solutions to any roadblocks
> * [ ]  Collect notes and complete `outcome` section above

Really loved how you have broken the task into smaller actionable tasks!

**Comment by cloudguruab** [comment]
Thank you! It definitely helps, and I appreciate the help. I will ping you if I find anything else

**Comment by cloudguruab** [comment]
@scopsy Hey I have final changes to be commited to my local branch, but I noticed some issues with pushing due to linting rules. I would love some clarity on the following: 

```
⧗   input: fix #67
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings 
```

**Comment by scopsy** [comment]
@cloudguruab Sounds like commitizen issue, try `git commit -m "--your message here--" --no-verify` 

I'll take a look at commitizen soon, had this issue yesterday aswell :|

**Comment by scopsy** [comment]
Just pushed a fix for master, you can pull it from there :)

**Comment by cloudguruab** [comment]
Thanks! Pushing my branch soon.

**Comment by scopsy** [comment]
@cloudguruab Thank you so much for all the help 🎉
